# Model analysis

#### Required libraries

In [1]:
import numpy as np
import pandas as pd
import json
import pickle
import matplotlib.pyplot as plt

from sklearn.model_selection import GridSearchCV, train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.svm import SVC
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier, RandomForestClassifier

import warnings
warnings.filterwarnings("ignore")

### Data preparation

In [2]:
data = pd.read_csv('../data/extension/csv/data.csv')
data.replace('?', np.NAN, inplace=True)
data[data.columns.drop(['year', 'X65'])] = data[data.columns.drop(['year', 'X65'])].astype(float)
data[['year', 'X65']] = data[['year', 'X65']].astype('category')
    

useless_col = data.isna().sum()[data.isna().sum() > 5000].index
data.drop(useless_col, axis=1, inplace=True)
useless_row = data.isna().sum(axis=1)[data.isna().sum(axis=1) > 10].index
data.drop(useless_row, axis=0, inplace=True)
data.fillna(data.mean(), inplace=True)
data = data.sample(frac=1)
data.shape, useless_col

((43184, 64), Index(['X21', 'X37'], dtype='object'))

#### Train data and test data

To get a balanced dataset that is fairly dependant on each year :

In [3]:
train_ = pd.DataFrame()
test_ = pd.DataFrame()
for year in data.year.unique():
    tr, ts = train_test_split(data[data.year == year], test_size=0.2, random_state=9)
    train_ = train_.append(tr, ignore_index=True)
    test_ = test_.append(ts, ignore_index=True)

train_.shape, test_.shape

((34545, 64), (8639, 64))

#### Data standardization

In [4]:
categ = ['year', 'X65']

scaler =  StandardScaler()
scaler.fit(train_.drop(columns=categ))

train = pd.DataFrame(scaler.transform(train_.drop(columns=categ)), 
                      columns=train_.columns.drop(categ))
test = pd.DataFrame(scaler.transform(test_.drop(columns=categ)), 
                     columns=test_.columns.drop(categ))

train = pd.concat([train, train_[categ]], axis=1)
test = pd.concat([test, test_[categ]], axis=1)

In [5]:
train_y = train.pop('X65')
train_x = train.copy()

test_y = test.pop('X65')
test_x = test.copy()

#### Save scaler used for standardize train set

In [6]:
with open('saved_model/scaler.sav', 'wb') as f:
    pickle.dump(scaler, f)

#### Encode categorical variable : year

In [7]:
train_x = pd.get_dummies(train_x)
test_x = pd.get_dummies(test_x)

train_x.shape, test_x.shape

((34545, 67), (8639, 67))

### Model testing

12 max features because in visualisation part, we saw that only 12 was needed to reach the biggest parts of information contained in dataset

#### Logistic regression

In [8]:
lr = LogisticRegression()
cross_val_score(lr, train_x, train_y, cv=5)

array([0.951802  , 0.95035461, 0.95064409, 0.36387321, 0.95035461])

In [9]:
params = dict(solver=['newton-cg', 'sag'], C=[1, 2, 3])
lr = LogisticRegression(n_jobs=-1)
grid = GridSearchCV(lr, params, cv=3, n_jobs=-1)
grid.fit(train_x, train_y)
grid.cv_results_
print(lr)
print("\n".join([f"for {x} => mean : {y}" for x,y in zip(
                     grid.cv_results_['params'], grid.cv_results_['mean_test_score']
                 )]))
print(grid.best_estimator_)

LogisticRegression(n_jobs=-1)
for {'C': 1, 'solver': 'newton-cg'} => mean : 0.9512230424084528
for {'C': 1, 'solver': 'sag'} => mean : 0.9512230424084528
for {'C': 2, 'solver': 'newton-cg'} => mean : 0.9510204081632653
for {'C': 2, 'solver': 'sag'} => mean : 0.9512230424084528
for {'C': 3, 'solver': 'newton-cg'} => mean : 0.9510204081632653
for {'C': 3, 'solver': 'sag'} => mean : 0.9512230424084528
LogisticRegression(C=1, n_jobs=-1, solver='newton-cg')


In [10]:
with open('saved_model/lr.sav', 'wb') as f:
    pickle.dump(grid.best_estimator_, f)

#### Linear Discriminant Analysis

In [11]:
lda = LDA(solver='svd', tol=1e-4)
cross_val_score(lda, train_x, train_y, cv=5)

array([0.9510783 , 0.94847301, 0.94963092, 0.35837314, 0.94905196])

In [12]:
params = dict(solver=['svd', 'lsqr'], tol=[1e-3, 1e-4, 1e-5])
lda = LDA()
grid = GridSearchCV(lda, params, cv=5, n_jobs=-1)
grid.fit(train_x, train_y)
grid.cv_results_
print(lda)
print("\n".join([f"for {x} => mean : {y}" 
                 for x,y in zip(
                     grid.cv_results_['params'], 
                     grid.cv_results_['mean_test_score'])]
               ))
print(grid.best_estimator_)

LinearDiscriminantAnalysis()
for {'solver': 'svd', 'tol': 0.001} => mean : 0.8313214647561151
for {'solver': 'svd', 'tol': 0.0001} => mean : 0.8313214647561151
for {'solver': 'svd', 'tol': 1e-05} => mean : 0.8313214647561151
for {'solver': 'lsqr', 'tol': 0.001} => mean : 0.7702706614560719
for {'solver': 'lsqr', 'tol': 0.0001} => mean : 0.7702706614560719
for {'solver': 'lsqr', 'tol': 1e-05} => mean : 0.7702706614560719
LinearDiscriminantAnalysis(tol=0.001)


In [13]:
with open('saved_model/lda.sav', 'wb') as f:
    pickle.dump(grid.best_estimator_, f)

#### Random Forest

In [14]:
rf = RandomForestClassifier(n_jobs=-1, random_state=9)
cross_val_score(rf, train_x, train_y, cv=3)

array([0.96691272, 0.96448111, 0.96552323])

In [15]:
params = dict(criterion=['gini'], max_depth=[15, 45, 50, 100, 200])
rf = RandomForestClassifier(n_jobs=-1, random_state=9)

grid = GridSearchCV(rf, params, cv=3, n_jobs=-1)
grid.fit(train_x, train_y)
grid.cv_results_
print(rf)
print("\n".join([f"for {x} => mean : {y}" 
                 for x,y in zip(
                     grid.cv_results_['params'], 
                     grid.cv_results_['mean_test_score'])]
               ))
print(grid.best_estimator_)

RandomForestClassifier(n_jobs=-1, random_state=9)
for {'criterion': 'gini', 'max_depth': 15} => mean : 0.9655811260674483
for {'criterion': 'gini', 'max_depth': 45} => mean : 0.9656390215660733
for {'criterion': 'gini', 'max_depth': 50} => mean : 0.9656390215660733
for {'criterion': 'gini', 'max_depth': 100} => mean : 0.9656390215660733
for {'criterion': 'gini', 'max_depth': 200} => mean : 0.9656390215660733
RandomForestClassifier(max_depth=45, n_jobs=-1, random_state=9)


In [16]:
with open('saved_model/rf.sav', 'wb') as f:
    pickle.dump(grid.best_estimator_, f)

#### Gradient Boosting

In [17]:
gbm = GradientBoostingClassifier()
cross_val_score(gbm, train_x, train_y, cv=5)

array([0.97119699, 0.96671009, 0.96801274, 0.37067593, 0.96801274])

In [18]:
params = dict(n_estimators=[100, 300], max_depth=[3,5,7])
gbm = GradientBoostingClassifier(random_state=9)

grid = GridSearchCV(gbm, params, cv=3, n_jobs=-1)
grid.fit(train_x, train_y)
grid.cv_results_
print(gbm)
print("\n".join([f"for {x} => mean : {y}" 
                 for x,y in zip(
                     grid.cv_results_['params'], 
                     grid.cv_results_['mean_test_score'])]
               ))
print(grid.best_estimator_)

GradientBoostingClassifier(random_state=9)
for {'max_depth': 3, 'n_estimators': 100} => mean : 0.9688522217397596
for {'max_depth': 3, 'n_estimators': 300} => mean : 0.9711969894340715
for {'max_depth': 5, 'n_estimators': 100} => mean : 0.9718048921696338
for {'max_depth': 5, 'n_estimators': 300} => mean : 0.9731364886380084
for {'max_depth': 7, 'n_estimators': 100} => mean : 0.9715154146765089
for {'max_depth': 7, 'n_estimators': 300} => mean : 0.9737443913735708
GradientBoostingClassifier(max_depth=7, n_estimators=300, random_state=9)


In [19]:
with open('saved_model/gbm.sav', 'wb') as f:
    pickle.dump(grid.best_estimator_, f)

#### SVM

In [8]:
svm = SVC()
cross_val_score(svm, train_x, train_y, cv=5)

array([0.95238095, 0.95238095, 0.95223621, 0.95238095, 0.95238095])

In [ ]:
params = dict(C=[1, 2], 
              kernel=['linear', 'rbf'])
svm = SVC(random_state=9)

grid = GridSearchCV(svm, params, cv=3, n_jobs=-1)
grid.fit(train_x, train_y)
grid.cv_results_
print(svm)
print("\n".join([f"for {x} => mean : {y}" 
                 for x,y in zip(
                     grid.cv_results_['params'], 
                     grid.cv_results_['mean_test_score'])]
               ))
print(grid.best_estimator_)

In [9]:
svm = SVC()
svm.fit(train_x, train_y)
with open('saved_model/svm.sav', 'wb') as f:
    pickle.dump(svm, f)

#### Bonus neural network : MultiLayer Perceptron

In [10]:
mlp = MLPClassifier()
mlp.fit(train_x, train_y)
mlp.score(train_x, train_y)

0.9617021276595744

In [ ]:
params = dict(hidden_layer_sizes=[100, 120], 
              activation=['relu', 'tanh'])
mlp = MLPClassifier(random_state=9)

grid = GridSearchCV(mlp, params, cv=3, n_jobs=-1)
grid.fit(train_x, train_y)
grid.cv_results_
print(mlp)
print("\n".join([f"for {x} => mean : {y}" 
                 for x,y in zip(
                     grid.cv_results_['params'], 
                     grid.cv_results_['mean_test_score'])]
               ))
print(grid.best_estimator_)

In [11]:
with open('saved_model/mlp.sav', 'wb') as f:
    pickle.dump(mlp, f)

### Underlying variables

In [18]:
with open('../data/udata_description.json', 'r') as f:
    udesc = json.loads(f.read())
    udesc['U35'] = 'bankrupt'

In [19]:
udata = pd.read_csv('../data/extension/csv/udata.csv')
udata.head()
udata.replace(np.inf, np.NAN, inplace=True)
useless_col = udata.isna().sum()[udata.isna().sum() > 5000].index
udata.drop(useless_col, axis=1, inplace=True)
useless_row = udata.isna().sum(axis=1)[udata.isna().sum(axis=1) > 5].index
udata.drop(useless_row, axis=0, inplace=True)
udata.fillna(udata.mean(), inplace=True)
udata.shape, [udesc[var] for var in useless_col]

((43246, 33), ['financial expenses', 'receivables', 'sales (n) / sales (n-1)'])

In [20]:
train_ = pd.DataFrame()
test_ = pd.DataFrame()
for year in udata.year.unique():
    tr, ts = train_test_split(udata[udata.year == year], test_size=0.2, random_state=9)
    train_ = train_.append(tr, ignore_index=True)
    test_ = test_.append(ts, ignore_index=True)

categ = ['year', 'U35']

uscaler =  StandardScaler()
uscaler.fit(train_.drop(columns=categ))

train = pd.DataFrame(uscaler.transform(train_.drop(columns=categ)), 
                      columns=train_.columns.drop(categ))
test = pd.DataFrame(uscaler.transform(test_.drop(columns=categ)), 
                     columns=test_.columns.drop(categ))

#### Save scaler used for standardize train set

In [21]:
with open('saved_model/uscaler.sav', 'wb') as f:
    pickle.dump(uscaler, f)

In [22]:
train = pd.concat([train, train_[categ]], axis=1)
test = pd.concat([test, test_[categ]], axis=1)
train_y = train.pop('U35')
train_x = train.copy()
test_y = test.pop('U35')
test_x = test.copy()

train_x = pd.get_dummies(train_x)
test_x = pd.get_dummies(test_x)

train_x.shape, train_y.shape

((34594, 36), (34594,))

### Test

#### On logistic regression

In [23]:
lr = LogisticRegression()
cross_val_score(lr, train_x, train_y, cv=5)

array([0.95129354, 0.94999277, 0.95100448, 0.95129354, 0.9524429 ])

In [24]:
params = dict(solver=['newton-cg', 'sag'], C=[1, 2, 3])
lr = LogisticRegression(n_jobs=-1)
grid = GridSearchCV(lr, params, cv=3, n_jobs=-1)
grid.fit(train_x, train_y)
grid.cv_results_
print(lr)
print("\n".join([f"for {x} => mean : {y}" for x,y in zip(
                     grid.cv_results_['params'], grid.cv_results_['mean_test_score']
                 )]))
print(grid.best_estimator_)

LogisticRegression(n_jobs=-1)
for {'C': 1, 'solver': 'newton-cg'} => mean : 0.7590855965147822
for {'C': 1, 'solver': 'sag'} => mean : 0.9512054120970402
for {'C': 2, 'solver': 'newton-cg'} => mean : 0.7472623927823733
for {'C': 2, 'solver': 'sag'} => mean : 0.9512054120970402
for {'C': 3, 'solver': 'newton-cg'} => mean : 0.7436200373925544
for {'C': 3, 'solver': 'sag'} => mean : 0.9512054120970402
LogisticRegression(C=1, n_jobs=-1, solver='sag')


In [25]:
with open('saved_model/ulr.sav', 'wb') as f:
    pickle.dump(grid.best_estimator_, f)

it appears that there is a tiny increasing with this dataset of underlying variable, let's test it on 
our best model, the MLP 

In [26]:
mlp = MLPClassifier()
mlp.fit(train_x, train_y)
mlp.score(train_x, train_y)

0.9693010348615367

In [27]:
with open('saved_model/umlp.sav', 'wb') as f:
    pickle.dump(mlp, f)